### PR TITLE
 Menu with Icons (Proposal)

### PR DESCRIPTION
**Pull request by esnya**
New menu with icons.  How about this UI design?

#40 is required to view valid diff.

Preview

### CODE REVIEW

**Comment by FairlySadPanda** [comment]
Looks solid for the default UI. M.O.O.N. is making a contribution I'll probably be putting up as a separate prefab, as it'd be nice to provide the user with good quality options.

**Comment by FairlySadPanda** [comment]
Still intend to merge this, have been busy. Note that further PRs will need you to sign the CLA! https://cla-assistant.io/FairlySadPanda/vrcbce

(Am obviously being more cautious w/ rights now given that I nearly got DMCA'd off this platform...)

**Comment by esnya** [comment]
I'm also very cautious about licensing.
If you want to merge it as one of the additional UI variations, shall I make a Prefab Variant?

**Comment by FairlySadPanda** [comment]
@esnya Accepted!

**Comment by FairlySadPanda** [comment]
Note that I might have screwed something up in the integration. I've had to try and get both your edits and M.O.O.N's playing nice in the same PoolMenu.cs file. You might want to review the merge.

**Comment by esnya** [comment]
I tested on single player, it seems to be works. :+1:
I'll continue to test on multi players...

**Pull request merged**
